export const getSkillChoices = () => {
  return [
    { id: "react", name: "React" },
    { id: "react-native", name: "React Native" },
    { id: "node", name: "Node" },
    { id: "express", name: "Express" },
    { id: "mongodb", name: "MongoDB" },
    { id: "firebase", name: "Firebase" },
    { id: "aws", name: "AWS" },
    { id: "azure", name: "Azure" },
    { id: "gcp", name: "GCP" },
    { id: "python", name: "Python" },
    { id: "c", name: "C" },
    { id: "c++", name: "C++" },
    { id: "c#", name: "C#" },
    { id: "java", name: "Java" },
    { id: "kotlin", name: "Kotlin" },
    { id: "swift", name: "Swift" },
    { id: "dart", name: "Dart" },
    { id: "php", name: "PHP" },
    { id: "ruby", name: "Ruby" },
    { id: "go", name: "Go" },
    { id: "rust", name: "Rust" },
    { id: "haskell", name: "Haskell" },
    { id: "scala", name: "Scala" },
    { id: "clojure", name: "Clojure" },
    { id: "elixir", name: "Elixir" },
    { id: "erlang", name: "Erlang" },
    { id: "r", name: "R" },
    { id: "sql", name: "SQL" },
    { id: "mysql", name: "MySQL" },
    { id: "postgresql", name: "PostgreSQL" },
    { id: "redis", name: "Redis" },
    { id: "graphql", name: "GraphQL" },
    { id: "apollo", name: "Apollo" },
    { id: "relay", name: "Relay" },
    { id: "redux", name: "Redux" },
    { id: "hadoop", name: "Hadoop" },
    { id: "spark", name: "Spark" },
    { id: "hive", name: "Hive" },
    { id: "kafka", name: "Kafka" },
    { id: "rabbitmq", name: "RabbitMQ" },
    { id: "kubernetes", name: "Kubernetes" },
    { id: "docker", name: "Docker" },
    { id: "terraform", name: "Terraform" },
    { id: "ansible", name: "Ansible" },
    { id: "chef", name: "Chef" },
    { id: "puppet", name: "Puppet" },
    { id: "salt", name: "Salt" },
    { id: "linux", name: "Linux" },
    { id: "macos", name: "macOS" },
    { id: "windows", name: "Windows" },
    { id: "ios", name: "iOS" },
    { id: "android", name: "Android" },
    { id: "raspbian", name: "Raspbian" },
    { id: "arduino", name: "Arduino" },
    { id: "raspberrypi", name: "Raspberry Pi" },
    { id: "flutter", name: "Flutter" },
    { id: "unity", name: "Unity" },
    { id: "unreal", name: "Unreal" },
    { id: "godot", name: "Godot" },
    { id: "blender", name: "Blender" },
    { id: "photoshop", name: "Photoshop" },
    { id: "illustrator", name: "Illustrator" },
    { id: "gimp", name: "GIMP" },
    { id: "inkscape", name: "Inkscape" },
    { id: "figma", name: "Figma" },
    { id: "sketch", name: "Sketch" },
    { id: "adobexd", name: "Adobe XD" },
    { id: "premierepro", name: "Premiere Pro" },
    { id: "aftereffects", name: "After Effects" },
    { id: "nginx", name: "NGINX" },
    { id: "varnish", name: "Varnish" },
    { id: "apache", name: "Apache" },
    { id: "glsl", name: "GLSL" },
    { id: "hlsl", name: "HLSL" },
    { id: "cg", name: "Cg" },
    { id: "metal", name: "Metal" },
    { id: "spirv", name: "SPIR-V" },
    { id: "webgl", name: "WebGL" },
    { id: "opengl", name: "OpenGL" },
    { id: "vulkan", name: "Vulkan" },
    { id: "directx", name: "DirectX" },
  ];
};
